import { LineEdit, HorizontalBox, ScrollView, TabWidget, VerticalBox, Button, StandardButton, Slider, ComboBox, ListView, StandardListView, GroupBox, CheckBox } from "std-widgets.slint";
import { SplitList } from "split_list.slint";
import { PredictionField } from "prediction_field.slint";

struct FieldData {
    label: string,
    id: string,
    value: string,
    is_secret: bool,
}

component ConfigField {
    in-out property <FieldData> field_data;
    callback changed_value(string);

    //max-height: 60px;

    init => {
        // debug("Created Config Field");
    }


    VerticalLayout {
        min-height: 80px;
        max-height: 80px;
        padding-bottom: 25px;
        spacing: 3px;

        Text {
            text: field_data.label;
            vertical-alignment: center;
            font-weight: 700;
        }
        line_edit := LineEdit {
            input-type: field_data.is_secret ? InputType.password : InputType.text;
            text: field_data.value;

            changed text => {
                changed_value(self.text);
            }

            max-height: 20px;
        }
    }
}


export component MainWindow inherits Window {
    min-width: 200px;
    min-height: 150px;
    preferred-width: 970px;
    preferred-height: 770px;
    
    
    callback save_settings();
    callback on_resize(); 

    in-out property <bool> show_popup: false;
    in-out property <string> popup_text;

    // Properties read in Rust code
    in-out property <[FieldData]> config_fields: [
        { label: "Client ID", id: "client_id" },
        { label: "Client Secret", id: "client_secret", is_secret: true },
        { label: "Bot Username", id: "account" },
        { label: "Streamer Username", id: "channel" },
        { label: "Redirect URI", id: "redirect_uri" },
        { label: "Listener Address", id: "listener" },
    ];

    changed width => {
        debug("width: ", root.width);
        debug("height: ", root.height);
    }
    
    // Hack to redraw popup on window change since changing x of popup doesn't fucking work fucking retarded
    my_timer := Timer {
        interval: 1000ms;
        running: root.show_popup;
        triggered() => {
            popup.show();
        }
    }


    TabWidget {
        current-index: 1;

        Tab {
            title: "Config";


            ScrollView {
                VerticalLayout {
                    padding: 20px;
                    alignment: space-between;
    
                    for config_field[i] in config_fields : ConfigField {
                        field_data: config-field;

                        // so retarded
                        changed_value(line_edit_value) => {
                            config_fields[i].value = line_edit_value;
                            // debug(config_field.value);
                        }
                    }


                    HorizontalLayout {
                        alignment: end;

                        btn := Button {
                            text: "Save";
                            min-height: 30px;
    
                            min-width: 80px;
                            max-width: 100px;
                            preferred-width: 100px;
                        
                            clicked => {
                                root.save_settings();
                            }


                        }

                        test := Button {
                            text: "Show me";
                            clicked => {
                                root.popup_text = "You shouldn't see this :)";
                                root.show_popup = true;
                            }
                        }
                    }
                }
            }



        }
        prediction_manager_tab := Tab {
            title: "Tab 2";
            property <length> pm_padding: 20px;

            HorizontalLayout {
                width: 100%;

                left_side := VerticalLayout {
                    padding: pm_padding;
                    width: parent.width * 50%;
                    spacing: 30px;

                    make_active := HorizontalLayout {
                        spacing: 20px;
                        Button {
                            text: "make active";
                        }
                        Text {
                            vertical-alignment: center;
                            font-weight: 600;
                            text: "active: game name - cat name";
                        }
                    }

                    game_cat := HorizontalLayout {
                        spacing: 20px;
                        game_section := VerticalLayout {
                            height: 40px;
                            Text {
                                max-height: 40px;
                                
                                text: "Game";
                            }

                            ComboBox {
                                max-height: 40px;
                                model: ["Red Dead Redemption 2", "shit"];
                            }
                        }
                        cat_section := VerticalLayout {
                            Text {
                                text: "Category";
                            }
                            ComboBox {
                                model: ["any%", "100%"];
                            }
                        }
                    }

                    SplitList {
                        selected_changed => {
                            debug("from root: item changed, index is now ", self.selected_split_index);
                            name_field.value = "";
                        }
                    }
                }

                right_side := VerticalLayout {
                    width: parent.width * 50%;
                    padding: pm_padding;

                    // change type later to some custom struct
                    in-out property <[string]> pred_fields : [
                        "Title",
                        "Outcome 1",
                        "Outcome 2",
                        "Outcome 3",
                        "Outcome 4",
                        "Outcome 5",
                        "Outcome 6",
                        "Outcome 7",
                        "Outcome 8",
                        "Outcome 9",
                        "Outcome 10",
                        "Time Window", // probably not a string field
                    ];
                    
                    fields := VerticalLayout {
                        spacing: 6px;
                        padding-bottom: 20px;
                        // alignment: start; // TODO probably remove this shit for responsiveness
                        
                        name_field := PredictionField {
                            field_name: "Name";
                        }

                        auto_start_check := HorizontalLayout {
                            height: 30px;
                            Text {
                                text: "Auto start";
                                vertical-alignment: center;
                                width: 100px;
                            }
                            CheckBox {
                        
                            }
                        }

                        split_name_field := PredictionField {
                            field_name: "Split name";
                            padding-bottom: 30px;
                            field_value_changed(val) => {
                                debug(val);
                            }
                        }

                        for pred_field[i] in pred_fields : PredictionField {
                            // TODO create a similar live update function like with config fields
                            
                            field_name: pred-field;
                        }

                    }

                    HorizontalLayout {
                        spacing: 50px;
                        alignment: center;
                        Button {
                            max-width: 120px;
                            max-height: 70px;
                            preferred-width: 100px;
                            preferred-height: 20px;
                            text: "Save";
                        }

                        Button {
                            max-width: 120px;
                            max-height: 70px;
                            preferred-width: 100px;
                            preferred-height: 50px;
                            text: "Delete";
                        }
                    }
                }
            }
        }
    }

    // TODO: Make separate component for this since the default Dialog component sucks ass
    popup := PopupWindow {
        close-policy: no-auto-close;

        width: 200px;
        height: 100px;
        y: parent.height / 2 - self.height / 2;
        x: parent.width / 2 - self.width / 2;

        


        r := Rectangle {
            background: #292929;
            opacity: 100%;
            border-radius: 10px;
            border-color: red;
            border-width: 2px;
        }

        VerticalLayout {
            padding: 20px;
            alignment: center;
            spacing: 12px;

            Text {
                wrap: word-wrap;
                text: root.popup_text;
            }

            Button {
                text: "Ok";
                clicked => {
                    popup.close();
                    root.show_popup = false;
                }
            }
        }
    }
}
 