import { LineEdit, HorizontalBox, ScrollView, TabWidget, VerticalBox, Button, StandardButton, Slider } from "std-widgets.slint";

struct FieldData {
    label: string,
    id: string,
    value: string,
    is_secret: bool,
}

component ConfigField {
    in-out property <FieldData> field_data;
    callback changed_value(string);

    //max-height: 60px;

    init => {
        // debug("Created Config Field");
    }


    VerticalLayout {
        min-height: 80px;
        max-height: 80px;
        padding-bottom: 25px;
        spacing: 3px;

        Text {
            text: field_data.label;
            vertical-alignment: center;
            font-weight: 700;
        }
        line_edit := LineEdit {
            input-type: field_data.is_secret ? InputType.password : InputType.text;
            text: field_data.value;

            changed text => {
                changed_value(self.text);
            }

            max-height: 20px;
        }
    }
}


export component MainWindow inherits Window {
    min-width: 200px;
    min-height: 150px;
    preferred-width: 500px;
    preferred-height: 550px;

    callback save_settings();

    // Properties read in Rust code
    in-out property <[FieldData]> config_fields: [
        { label: "Client ID", id: "client_id" },
        { label: "Client Secret", id: "client_secret", is_secret: true },
        { label: "Bot Username", id: "account" },
        { label: "Streamer Username", id: "channel" },
        { label: "Redirect URI", id: "redirect_uri" },
        { label: "Listener Address", id: "listener" },
    ];
    in-out property <bool> show_test_dialog: false;


    TabWidget {
        Tab {
            title: "Config";


            ScrollView {
                VerticalLayout {
                    padding: 20px;
                    alignment: space-between;
    
                    for config_field[i] in config_fields : ConfigField {
                        field_data: config-field;

                        // so retarded
                        changed_value(line_edit_value) => {
                            config_fields[i].value = line_edit_value;
                            // debug(config_field.value);
                        }
                    }


                    HorizontalLayout {
                        alignment: end;

                        btn := Button {
                            text: "Save";
                            min-height: 30px;
    
                            min-width: 80px;
                            max-width: 100px;
                            preferred-width: 100px;
                        
                            clicked => {
                                root.save_settings();
                            }


                        }

                        test := Button {
                            text: "Show me!";

                            clicked => {
                                root.show_test_dialog = true;
                                popup.show();
                            }
                        }
                    }
                }
            }



        }
        Tab {
            title: "Tab 2";
        }
    }

    // Make separate component for this since the default Dialog component sucks ass
    popup := PopupWindow {
        close-policy: no-auto-close;

        width: root.preferred-width;
        height: 100px;

        x: parent.width / 2 - self.width / 2;
        y: parent.height / 2 - self.height / 2;

        r := Rectangle {
            background: #292929;
            opacity: 100%;
            border-radius: 10px;
            border-color: red;
            border-width: 2px;
        }

        VerticalLayout {
            padding: 20px;
            alignment: center;
            spacing: 12px;

            Text {
                wrap: word-wrap;
                text: "Click OK if you're fkn retarded like this framework";
            }

            Button {
                text: "Ok";
                clicked => {
                    popup.close();
                }
            }
        }



    }



}