import { ListView, GroupBox, StandardListView, Button } from "std-widgets.slint";

struct DataObject {
    split_name: string,
    has_prediction: bool,

}

export component SplitList {
    callback selected_changed;

    in-out property <DataObject> selected_split;
    in-out property <int> selected_split_index: -1;


    VerticalLayout {

        Rectangle {
            background: gray;
            border-color: orange;
            border-width: 2px;

            VerticalLayout {
                padding: 20px;
                padding-top: 0px;

                GroupBox {
                    title: "Splits";

                    split_list := ListView {
                        in-out property <[DataObject]> objects: [
                            { split_name: "item 1" },
                            { split_name: "item 2" },
                            { split_name: "item 3" },
                            { split_name: "item 4" },
                        ];
                
                        for data[i] in objects : rec :=
                        Rectangle {
                            background: #161d27;
                            height: 25px;

                            states [
                                active-hover when ta.has-hover: {
                                    rec.background: #0f1319;
                                }

                                selected when root.selected_split_index == i: {
                                    rec.background: #0f1319;
                                }
                                // active-hover when active && ta.has-hover: {
                                //     label.text: "Active\nHover";
                                //     root.background: green;
                                // }
                                // inactive when !active: {
                                //     label.text: "Inactive";
                                //     root.background: gray;
                                // }
                            ]
                            HorizontalLayout {
                                padding-left: 3px;
                                alignment: start;
                                spacing: 6px;
                                
                                if root.selected_split_index == i: Image {
                                    source: @image-url("icons/star.png");
                                    // colorize: white;
                                    width: 16px;
                                }
                                Text {
                                    text: data.split_name;
                                    font-weight: 700;
                                    color: white;
                                    vertical-alignment: center;
                                }
                            }
                            
                            ta := TouchArea {
                                mouse-cursor: pointer;
                                clicked => {
                                    root.selected_split = data;
                                    root.selected_split_index = i;
                                    
                                    root.selected_changed();
                                }
                            }

                        }
                
                    }
                }
            }
        }
        Button {
            text: "click me";
            clicked => {
                debug("Selected index is ", root.selected_split_index);
                debug("Selected item is: ", root.selected_split.split_name);
            }
        }
    }



}