
import { ListView, GroupBox, StandardListView, Button } from "std-widgets.slint";

struct DataObject {
    text: string,
    background: color,
    color: color,
}

export component Test {
    width: 350px;
    height: 300px;

    in-out property <DataObject> selected_split <=> split_list.selected;
    in-out property <int> selected_split_index <=> split_list.selected_index;

    VerticalLayout {
        padding: 20px;

        Rectangle {
            background: blue;
            border-color: pink;
            border-width: 2px;

            VerticalLayout {
                padding: 20px;

                GroupBox {
                    width: 100%;
                    title: "My list";

                    split_list := ListView {
                        in-out property <[DataObject]> objects: [
                            { text: "item 1", background: Colors.red, color: Colors.white },
                            { text: "item 2", background: Colors.red, color: Colors.white },
                            { text: "item 3", background: Colors.red, color: Colors.white },
                        ];

                        in-out property <DataObject> selected;
                        in-out property <int> selected_index: -1;
                
                        for data[i] in objects : rec :=
                        Rectangle {
                            states [
                                active-hover when ta.has-hover: {
                                    rec.background: pink;
                                }

                                selected when split_list.selected_index == i: {
                                    rec.background: Colors.pink;
                                }
                                // active-hover when active && ta.has-hover: {
                                //     label.text: "Active\nHover";
                                //     root.background: green;
                                // }
                                // inactive when !active: {
                                //     label.text: "Inactive";
                                //     root.background: gray;
                                // }
                            ]

                            background: data.background;
                            opacity: 80%;
                            HorizontalLayout {
                                padding-left: 10px;
                                alignment: start;
                                Text {
                                    text: data.text;
                                    font-weight: 700;
                                    color: black;
                                }
                            }
                            
                            ta := TouchArea {
                                clicked => {
                                    split_list.selected = data;
                                    split_list.selected_index = i;
                                    // parent.background = Colors.green;
                                }
                            }

                        }
                
                    }
                }
            }
        }
        Button {
            text: "click me";
            clicked => {
                debug("Selected index is ", root.selected_split_index);
                debug("Selected item is: ", root.selected_split.text);
            }
        }
    }



}